apiVersion: v1alpha1
kind: GoRagChatbotKnowledgeBaseConfig
spec:
  docs:
    # - type: "http"
    #   collection: "OpenShift 4.18 Bare Metal Installation"
    #   httpSources:    
    #   - url: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html-single/installing_on_bare_metal/index
    #     fileType: "html"
    #     urlFilter:
    #       allowed:
    #       - "install"
    #       skip:
    #       - "#"
    #     recursionLevels: 3
    #     allowedDomains:
    #     - docs.redhat.com
    #   metadata:
    #     action: "installation"
    #     platform: "bare metal"
    #     version: "4.18"
    - type: "http"
      collection: "OpenShift 4.18 vSphere Installation"
      metadata:
        action: "installation"
        platform: "vsphere"
        version: "4.18"      
      httpSources:    
      - url: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html-single/installing_on_vmware_vsphere/index
        fileType: "html"
        urlFilter:
          allowed:
          - "install"
          skip:
          - "#"
        recursionLevels: 3
        allowedDomains:
        - docs.redhat.com        
